/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTaskRequest
 */
export interface DeleteTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof DeleteTaskRequest
     */
    taskId?: string;
}

/**
 * Check if a given object implements the DeleteTaskRequest interface.
 */
export function instanceOfDeleteTaskRequest(value: object): boolean {
    return true;
}

export function DeleteTaskRequestFromJSON(json: any): DeleteTaskRequest {
    return DeleteTaskRequestFromJSONTyped(json, false);
}

export function DeleteTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
    };
}

export function DeleteTaskRequestToJSON(value?: DeleteTaskRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'taskId': value['taskId'],
    };
}

