/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTaskResponseBaseResponse
 */
export interface DeleteTaskResponseBaseResponse {
    /**
     * 
     * @type {number}
     * @memberof DeleteTaskResponseBaseResponse
     */
    code?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DeleteTaskResponseBaseResponse
     */
    readonly success?: boolean;
    /**
     * 
     * @type {object}
     * @memberof DeleteTaskResponseBaseResponse
     */
    result?: object;
    /**
     * 
     * @type {string}
     * @memberof DeleteTaskResponseBaseResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteTaskResponseBaseResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the DeleteTaskResponseBaseResponse interface.
 */
export function instanceOfDeleteTaskResponseBaseResponse(value: object): boolean {
    return true;
}

export function DeleteTaskResponseBaseResponseFromJSON(json: any): DeleteTaskResponseBaseResponse {
    return DeleteTaskResponseBaseResponseFromJSONTyped(json, false);
}

export function DeleteTaskResponseBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTaskResponseBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'success': json['success'] == null ? undefined : json['success'],
        'result': json['result'] == null ? undefined : json['result'],
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function DeleteTaskResponseBaseResponseToJSON(value?: Omit<DeleteTaskResponseBaseResponse, 'success'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'result': value['result'],
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

