/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExcuteOnceRequest
 */
export interface ExcuteOnceRequest {
    /**
     * 
     * @type {string}
     * @memberof ExcuteOnceRequest
     */
    taskId?: string;
}

/**
 * Check if a given object implements the ExcuteOnceRequest interface.
 */
export function instanceOfExcuteOnceRequest(value: object): boolean {
    return true;
}

export function ExcuteOnceRequestFromJSON(json: any): ExcuteOnceRequest {
    return ExcuteOnceRequestFromJSONTyped(json, false);
}

export function ExcuteOnceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExcuteOnceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
    };
}

export function ExcuteOnceRequestToJSON(value?: ExcuteOnceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'taskId': value['taskId'],
    };
}

