/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecutorClient
 */
export interface ExecutorClient {
    /**
     * 
     * @type {string}
     * @memberof ExecutorClient
     */
    groupName?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutorClient
     */
    connectionId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExecutorClient
     */
    handelrs?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ExecutorClient
     */
    startTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof ExecutorClient
     */
    clientId?: string;
}

/**
 * Check if a given object implements the ExecutorClient interface.
 */
export function instanceOfExecutorClient(value: object): boolean {
    return true;
}

export function ExecutorClientFromJSON(json: any): ExecutorClient {
    return ExecutorClientFromJSONTyped(json, false);
}

export function ExecutorClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutorClient {
    if (json == null) {
        return json;
    }
    return {
        
        'groupName': json['groupName'] == null ? undefined : json['groupName'],
        'connectionId': json['connectionId'] == null ? undefined : json['connectionId'],
        'handelrs': json['handelrs'] == null ? undefined : json['handelrs'],
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
    };
}

export function ExecutorClientToJSON(value?: ExecutorClient | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groupName': value['groupName'],
        'connectionId': value['connectionId'],
        'handelrs': value['handelrs'],
        'startTime': value['startTime'] == null ? undefined : ((value['startTime']).toISOString()),
        'clientId': value['clientId'],
    };
}

