/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetNext5TriggertimesResponse } from './GetNext5TriggertimesResponse';
import {
    GetNext5TriggertimesResponseFromJSON,
    GetNext5TriggertimesResponseFromJSONTyped,
    GetNext5TriggertimesResponseToJSON,
} from './GetNext5TriggertimesResponse';

/**
 * 
 * @export
 * @interface GetNext5TriggertimesResponseBaseResponse
 */
export interface GetNext5TriggertimesResponseBaseResponse {
    /**
     * 
     * @type {number}
     * @memberof GetNext5TriggertimesResponseBaseResponse
     */
    code?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetNext5TriggertimesResponseBaseResponse
     */
    readonly success?: boolean;
    /**
     * 
     * @type {GetNext5TriggertimesResponse}
     * @memberof GetNext5TriggertimesResponseBaseResponse
     */
    result?: GetNext5TriggertimesResponse;
    /**
     * 
     * @type {string}
     * @memberof GetNext5TriggertimesResponseBaseResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof GetNext5TriggertimesResponseBaseResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the GetNext5TriggertimesResponseBaseResponse interface.
 */
export function instanceOfGetNext5TriggertimesResponseBaseResponse(value: object): boolean {
    return true;
}

export function GetNext5TriggertimesResponseBaseResponseFromJSON(json: any): GetNext5TriggertimesResponseBaseResponse {
    return GetNext5TriggertimesResponseBaseResponseFromJSONTyped(json, false);
}

export function GetNext5TriggertimesResponseBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNext5TriggertimesResponseBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'success': json['success'] == null ? undefined : json['success'],
        'result': json['result'] == null ? undefined : GetNext5TriggertimesResponseFromJSON(json['result']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function GetNext5TriggertimesResponseBaseResponseToJSON(value?: Omit<GetNext5TriggertimesResponseBaseResponse, 'success'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'result': GetNext5TriggertimesResponseToJSON(value['result']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

