/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListTopTaskLogResponse } from './ListTopTaskLogResponse';
import {
    ListTopTaskLogResponseFromJSON,
    ListTopTaskLogResponseFromJSONTyped,
    ListTopTaskLogResponseToJSON,
} from './ListTopTaskLogResponse';

/**
 * 
 * @export
 * @interface ListTopTaskLogResponseBaseResponse
 */
export interface ListTopTaskLogResponseBaseResponse {
    /**
     * 
     * @type {number}
     * @memberof ListTopTaskLogResponseBaseResponse
     */
    code?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListTopTaskLogResponseBaseResponse
     */
    readonly success?: boolean;
    /**
     * 
     * @type {ListTopTaskLogResponse}
     * @memberof ListTopTaskLogResponseBaseResponse
     */
    result?: ListTopTaskLogResponse;
    /**
     * 
     * @type {string}
     * @memberof ListTopTaskLogResponseBaseResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTopTaskLogResponseBaseResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the ListTopTaskLogResponseBaseResponse interface.
 */
export function instanceOfListTopTaskLogResponseBaseResponse(value: object): boolean {
    return true;
}

export function ListTopTaskLogResponseBaseResponseFromJSON(json: any): ListTopTaskLogResponseBaseResponse {
    return ListTopTaskLogResponseBaseResponseFromJSONTyped(json, false);
}

export function ListTopTaskLogResponseBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTopTaskLogResponseBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'success': json['success'] == null ? undefined : json['success'],
        'result': json['result'] == null ? undefined : ListTopTaskLogResponseFromJSON(json['result']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function ListTopTaskLogResponseBaseResponseToJSON(value?: Omit<ListTopTaskLogResponseBaseResponse, 'success'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'result': ListTopTaskLogResponseToJSON(value['result']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

