/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TopTaskLog } from './TopTaskLog';
import {
    TopTaskLogFromJSON,
    TopTaskLogFromJSONTyped,
    TopTaskLogToJSON,
} from './TopTaskLog';

/**
 * 
 * @export
 * @interface ListTopTaskLogResponse
 */
export interface ListTopTaskLogResponse {
    /**
     * 
     * @type {Array<TopTaskLog>}
     * @memberof ListTopTaskLogResponse
     */
    data?: Array<TopTaskLog>;
}

/**
 * Check if a given object implements the ListTopTaskLogResponse interface.
 */
export function instanceOfListTopTaskLogResponse(value: object): boolean {
    return true;
}

export function ListTopTaskLogResponseFromJSON(json: any): ListTopTaskLogResponse {
    return ListTopTaskLogResponseFromJSONTyped(json, false);
}

export function ListTopTaskLogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTopTaskLogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TopTaskLogFromJSON)),
    };
}

export function ListTopTaskLogResponseToJSON(value?: ListTopTaskLogResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TopTaskLogToJSON)),
    };
}

