/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskInfo } from './TaskInfo';
import {
    TaskInfoFromJSON,
    TaskInfoFromJSONTyped,
    TaskInfoToJSON,
} from './TaskInfo';

/**
 * 
 * @export
 * @interface ListTaskInfosResponse
 */
export interface ListTaskInfosResponse {
    /**
     * 
     * @type {string}
     * @memberof ListTaskInfosResponse
     */
    count?: string;
    /**
     * 
     * @type {Array<TaskInfo>}
     * @memberof ListTaskInfosResponse
     */
    rows?: Array<TaskInfo>;
}

/**
 * Check if a given object implements the ListTaskInfosResponse interface.
 */
export function instanceOfListTaskInfosResponse(value: object): boolean {
    return true;
}

export function ListTaskInfosResponseFromJSON(json: any): ListTaskInfosResponse {
    return ListTaskInfosResponseFromJSONTyped(json, false);
}

export function ListTaskInfosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTaskInfosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(TaskInfoFromJSON)),
    };
}

export function ListTaskInfosResponseToJSON(value?: ListTaskInfosResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(TaskInfoToJSON)),
    };
}

