/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListTaskInfosResponse } from './ListTaskInfosResponse';
import {
    ListTaskInfosResponseFromJSON,
    ListTaskInfosResponseFromJSONTyped,
    ListTaskInfosResponseToJSON,
} from './ListTaskInfosResponse';

/**
 * 
 * @export
 * @interface ListTaskInfosResponseBaseResponse
 */
export interface ListTaskInfosResponseBaseResponse {
    /**
     * 
     * @type {number}
     * @memberof ListTaskInfosResponseBaseResponse
     */
    code?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListTaskInfosResponseBaseResponse
     */
    readonly success?: boolean;
    /**
     * 
     * @type {ListTaskInfosResponse}
     * @memberof ListTaskInfosResponseBaseResponse
     */
    result?: ListTaskInfosResponse;
    /**
     * 
     * @type {string}
     * @memberof ListTaskInfosResponseBaseResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTaskInfosResponseBaseResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the ListTaskInfosResponseBaseResponse interface.
 */
export function instanceOfListTaskInfosResponseBaseResponse(value: object): boolean {
    return true;
}

export function ListTaskInfosResponseBaseResponseFromJSON(json: any): ListTaskInfosResponseBaseResponse {
    return ListTaskInfosResponseBaseResponseFromJSONTyped(json, false);
}

export function ListTaskInfosResponseBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTaskInfosResponseBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'success': json['success'] == null ? undefined : json['success'],
        'result': json['result'] == null ? undefined : ListTaskInfosResponseFromJSON(json['result']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function ListTaskInfosResponseBaseResponseToJSON(value?: Omit<ListTaskInfosResponseBaseResponse, 'success'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'result': ListTaskInfosResponseToJSON(value['result']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

