/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LisTaskLogsResponse } from './LisTaskLogsResponse';
import {
    LisTaskLogsResponseFromJSON,
    LisTaskLogsResponseFromJSONTyped,
    LisTaskLogsResponseToJSON,
} from './LisTaskLogsResponse';

/**
 * 
 * @export
 * @interface LisTaskLogsResponseBaseResponse
 */
export interface LisTaskLogsResponseBaseResponse {
    /**
     * 
     * @type {number}
     * @memberof LisTaskLogsResponseBaseResponse
     */
    code?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LisTaskLogsResponseBaseResponse
     */
    readonly success?: boolean;
    /**
     * 
     * @type {LisTaskLogsResponse}
     * @memberof LisTaskLogsResponseBaseResponse
     */
    result?: LisTaskLogsResponse;
    /**
     * 
     * @type {string}
     * @memberof LisTaskLogsResponseBaseResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof LisTaskLogsResponseBaseResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the LisTaskLogsResponseBaseResponse interface.
 */
export function instanceOfLisTaskLogsResponseBaseResponse(value: object): boolean {
    return true;
}

export function LisTaskLogsResponseBaseResponseFromJSON(json: any): LisTaskLogsResponseBaseResponse {
    return LisTaskLogsResponseBaseResponseFromJSONTyped(json, false);
}

export function LisTaskLogsResponseBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LisTaskLogsResponseBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'success': json['success'] == null ? undefined : json['success'],
        'result': json['result'] == null ? undefined : LisTaskLogsResponseFromJSON(json['result']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function LisTaskLogsResponseBaseResponseToJSON(value?: Omit<LisTaskLogsResponseBaseResponse, 'success'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'result': LisTaskLogsResponseToJSON(value['result']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

