/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskLog } from './TaskLog';
import {
    TaskLogFromJSON,
    TaskLogFromJSONTyped,
    TaskLogToJSON,
} from './TaskLog';

/**
 * 
 * @export
 * @interface LisTaskLogsResponse
 */
export interface LisTaskLogsResponse {
    /**
     * 
     * @type {string}
     * @memberof LisTaskLogsResponse
     */
    count?: string;
    /**
     * 
     * @type {Array<TaskLog>}
     * @memberof LisTaskLogsResponse
     */
    rows?: Array<TaskLog>;
}

/**
 * Check if a given object implements the LisTaskLogsResponse interface.
 */
export function instanceOfLisTaskLogsResponse(value: object): boolean {
    return true;
}

export function LisTaskLogsResponseFromJSON(json: any): LisTaskLogsResponse {
    return LisTaskLogsResponseFromJSONTyped(json, false);
}

export function LisTaskLogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LisTaskLogsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(TaskLogFromJSON)),
    };
}

export function LisTaskLogsResponseToJSON(value?: LisTaskLogsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(TaskLogToJSON)),
    };
}

