/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginCommand
 */
export interface LoginCommand {
    /**
     * 
     * @type {string}
     * @memberof LoginCommand
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof LoginCommand
     */
    password: string;
}

/**
 * Check if a given object implements the LoginCommand interface.
 */
export function instanceOfLoginCommand(value: object): boolean {
    if (!('userName' in value)) return false;
    if (!('password' in value)) return false;
    return true;
}

export function LoginCommandFromJSON(json: any): LoginCommand {
    return LoginCommandFromJSONTyped(json, false);
}

export function LoginCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'password': json['password'],
    };
}

export function LoginCommandToJSON(value?: LoginCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userName': value['userName'],
        'password': value['password'],
    };
}

