/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponse } from './LoginResponse';
import {
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
} from './LoginResponse';

/**
 * 
 * @export
 * @interface LoginResponseBaseResponse
 */
export interface LoginResponseBaseResponse {
    /**
     * 
     * @type {number}
     * @memberof LoginResponseBaseResponse
     */
    code?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponseBaseResponse
     */
    readonly success?: boolean;
    /**
     * 
     * @type {LoginResponse}
     * @memberof LoginResponseBaseResponse
     */
    result?: LoginResponse;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseBaseResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseBaseResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the LoginResponseBaseResponse interface.
 */
export function instanceOfLoginResponseBaseResponse(value: object): boolean {
    return true;
}

export function LoginResponseBaseResponseFromJSON(json: any): LoginResponseBaseResponse {
    return LoginResponseBaseResponseFromJSONTyped(json, false);
}

export function LoginResponseBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'success': json['success'] == null ? undefined : json['success'],
        'result': json['result'] == null ? undefined : LoginResponseFromJSON(json['result']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function LoginResponseBaseResponseToJSON(value?: Omit<LoginResponseBaseResponse, 'success'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'result': LoginResponseToJSON(value['result']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

