/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatisticInfos } from './StatisticInfos';
import {
    StatisticInfosFromJSON,
    StatisticInfosFromJSONTyped,
    StatisticInfosToJSON,
} from './StatisticInfos';

/**
 * 
 * @export
 * @interface StatisticsResponse
 */
export interface StatisticsResponse {
    /**
     * 
     * @type {StatisticInfos}
     * @memberof StatisticsResponse
     */
    taskInfos?: StatisticInfos;
    /**
     * 
     * @type {StatisticInfos}
     * @memberof StatisticsResponse
     */
    taskLogs?: StatisticInfos;
    /**
     * 
     * @type {StatisticInfos}
     * @memberof StatisticsResponse
     */
    servers?: StatisticInfos;
    /**
     * 
     * @type {StatisticInfos}
     * @memberof StatisticsResponse
     */
    workers?: StatisticInfos;
}

/**
 * Check if a given object implements the StatisticsResponse interface.
 */
export function instanceOfStatisticsResponse(value: object): boolean {
    return true;
}

export function StatisticsResponseFromJSON(json: any): StatisticsResponse {
    return StatisticsResponseFromJSONTyped(json, false);
}

export function StatisticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'taskInfos': json['taskInfos'] == null ? undefined : StatisticInfosFromJSON(json['taskInfos']),
        'taskLogs': json['taskLogs'] == null ? undefined : StatisticInfosFromJSON(json['taskLogs']),
        'servers': json['servers'] == null ? undefined : StatisticInfosFromJSON(json['servers']),
        'workers': json['workers'] == null ? undefined : StatisticInfosFromJSON(json['workers']),
    };
}

export function StatisticsResponseToJSON(value?: StatisticsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'taskInfos': StatisticInfosToJSON(value['taskInfos']),
        'taskLogs': StatisticInfosToJSON(value['taskLogs']),
        'servers': StatisticInfosToJSON(value['servers']),
        'workers': StatisticInfosToJSON(value['workers']),
    };
}

