/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatisticInfos
 */
export interface StatisticInfos {
    /**
     * 
     * @type {string}
     * @memberof StatisticInfos
     */
    count?: string;
}

/**
 * Check if a given object implements the StatisticInfos interface.
 */
export function instanceOfStatisticInfos(value: object): boolean {
    return true;
}

export function StatisticInfosFromJSON(json: any): StatisticInfos {
    return StatisticInfosFromJSONTyped(json, false);
}

export function StatisticInfosFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticInfos {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function StatisticInfosToJSON(value?: StatisticInfos | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
    };
}

