/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskLogDayTrend
 */
export interface TaskLogDayTrend {
    /**
     * 
     * @type {string}
     * @memberof TaskLogDayTrend
     */
    day?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskLogDayTrend
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskLogDayTrend
     */
    success?: number;
}

/**
 * Check if a given object implements the TaskLogDayTrend interface.
 */
export function instanceOfTaskLogDayTrend(value: object): boolean {
    return true;
}

export function TaskLogDayTrendFromJSON(json: any): TaskLogDayTrend {
    return TaskLogDayTrendFromJSONTyped(json, false);
}

export function TaskLogDayTrendFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskLogDayTrend {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'] == null ? undefined : json['day'],
        'total': json['total'] == null ? undefined : json['total'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function TaskLogDayTrendToJSON(value?: TaskLogDayTrend | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'day': value['day'],
        'total': value['total'],
        'success': value['success'],
    };
}

