/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskInfo
 */
export interface TaskInfo {
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    appid?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    handler?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    timeType?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    timeConf?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskInfo
     */
    attemptInterval?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskInfo
     */
    attemptMax?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    handleParams?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    scheduleMode?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    alarmType?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    alarmContent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TaskInfo
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TaskInfo
     */
    triggerNextTime?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskInfo
     */
    slot?: number;
}

/**
 * Check if a given object implements the TaskInfo interface.
 */
export function instanceOfTaskInfo(value: object): boolean {
    return true;
}

export function TaskInfoFromJSON(json: any): TaskInfo {
    return TaskInfoFromJSONTyped(json, false);
}

export function TaskInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'appid': json['appid'] == null ? undefined : json['appid'],
        'name': json['name'] == null ? undefined : json['name'],
        'handler': json['handler'] == null ? undefined : json['handler'],
        'description': json['description'] == null ? undefined : json['description'],
        'timeType': json['timeType'] == null ? undefined : json['timeType'],
        'timeConf': json['timeConf'] == null ? undefined : json['timeConf'],
        'attemptInterval': json['attemptInterval'] == null ? undefined : json['attemptInterval'],
        'attemptMax': json['attemptMax'] == null ? undefined : json['attemptMax'],
        'handleParams': json['handleParams'] == null ? undefined : json['handleParams'],
        'scheduleMode': json['scheduleMode'] == null ? undefined : json['scheduleMode'],
        'alarmType': json['alarmType'] == null ? undefined : json['alarmType'],
        'alarmContent': json['alarmContent'] == null ? undefined : json['alarmContent'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'triggerNextTime': json['triggerNextTime'] == null ? undefined : json['triggerNextTime'],
        'slot': json['slot'] == null ? undefined : json['slot'],
    };
}

export function TaskInfoToJSON(value?: TaskInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'appid': value['appid'],
        'name': value['name'],
        'handler': value['handler'],
        'description': value['description'],
        'timeType': value['timeType'],
        'timeConf': value['timeConf'],
        'attemptInterval': value['attemptInterval'],
        'attemptMax': value['attemptMax'],
        'handleParams': value['handleParams'],
        'scheduleMode': value['scheduleMode'],
        'alarmType': value['alarmType'],
        'alarmContent': value['alarmContent'],
        'enabled': value['enabled'],
        'triggerNextTime': value['triggerNextTime'],
        'slot': value['slot'],
    };
}

