/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskLogDayTrend } from './TaskLogDayTrend';
import {
    TaskLogDayTrendFromJSON,
    TaskLogDayTrendFromJSONTyped,
    TaskLogDayTrendToJSON,
} from './TaskLogDayTrend';

/**
 * 
 * @export
 * @interface TaskLogsDayTrendResponse
 */
export interface TaskLogsDayTrendResponse {
    /**
     * 
     * @type {Array<TaskLogDayTrend>}
     * @memberof TaskLogsDayTrendResponse
     */
    data?: Array<TaskLogDayTrend>;
}

/**
 * Check if a given object implements the TaskLogsDayTrendResponse interface.
 */
export function instanceOfTaskLogsDayTrendResponse(value: object): boolean {
    return true;
}

export function TaskLogsDayTrendResponseFromJSON(json: any): TaskLogsDayTrendResponse {
    return TaskLogsDayTrendResponseFromJSONTyped(json, false);
}

export function TaskLogsDayTrendResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskLogsDayTrendResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TaskLogDayTrendFromJSON)),
    };
}

export function TaskLogsDayTrendResponseToJSON(value?: TaskLogsDayTrendResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TaskLogDayTrendToJSON)),
    };
}

