/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskLog
 */
export interface TaskLog {
    /**
     * 
     * @type {string}
     * @memberof TaskLog
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskLog
     */
    taskId?: string;
    /**
     * 
     * @type {Date}
     * @memberof TaskLog
     */
    handleStart?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TaskLog
     */
    handleEnd?: Date;
    /**
     * 
     * @type {string}
     * @memberof TaskLog
     */
    handleResult?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskLog
     */
    handleStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskLog
     */
    handleClient?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskLog
     */
    alarmStatus?: number;
}

/**
 * Check if a given object implements the TaskLog interface.
 */
export function instanceOfTaskLog(value: object): boolean {
    return true;
}

export function TaskLogFromJSON(json: any): TaskLog {
    return TaskLogFromJSONTyped(json, false);
}

export function TaskLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskLog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'handleStart': json['handleStart'] == null ? undefined : (new Date(json['handleStart'])),
        'handleEnd': json['handleEnd'] == null ? undefined : (new Date(json['handleEnd'])),
        'handleResult': json['handleResult'] == null ? undefined : json['handleResult'],
        'handleStatus': json['handleStatus'] == null ? undefined : json['handleStatus'],
        'handleClient': json['handleClient'] == null ? undefined : json['handleClient'],
        'alarmStatus': json['alarmStatus'] == null ? undefined : json['alarmStatus'],
    };
}

export function TaskLogToJSON(value?: TaskLog | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'taskId': value['taskId'],
        'handleStart': value['handleStart'] == null ? undefined : ((value['handleStart'] as any).toISOString()),
        'handleEnd': value['handleEnd'] == null ? undefined : ((value['handleEnd'] as any).toISOString()),
        'handleResult': value['handleResult'],
        'handleStatus': value['handleStatus'],
        'handleClient': value['handleClient'],
        'alarmStatus': value['alarmStatus'],
    };
}

