/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopTaskLog
 */
export interface TopTaskLog {
    /**
     * 
     * @type {string}
     * @memberof TopTaskLog
     */
    taskId?: string;
    /**
     * 
     * @type {string}
     * @memberof TopTaskLog
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TopTaskLog
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TopTaskLog
     */
    count?: string;
}

/**
 * Check if a given object implements the TopTaskLog interface.
 */
export function instanceOfTopTaskLog(value: object): boolean {
    return true;
}

export function TopTaskLogFromJSON(json: any): TopTaskLog {
    return TopTaskLogFromJSONTyped(json, false);
}

export function TopTaskLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopTaskLog {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function TopTaskLogToJSON(value?: TopTaskLog | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'taskId': value['taskId'],
        'name': value['name'],
        'description': value['description'],
        'count': value['count'],
    };
}

