/* tslint:disable */
/* eslint-disable */
/**
 * OpenTask.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListClientsResponseBaseResponse,
} from '../models/index';
import {
    ListClientsResponseBaseResponseFromJSON,
    ListClientsResponseBaseResponseToJSON,
} from '../models/index';

export interface ListClientsRequest {
    pageNumber?: number;
    pageSize?: number;
}

/**
 * 
 */
export class ClientApi extends runtime.BaseAPI {

    /**
     */
    async listClientsRaw(requestParameters: ListClientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListClientsResponseBaseResponse>> {
        const queryParameters: any = {};

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Client/ListClients`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListClientsResponseBaseResponseFromJSON(jsonValue));
    }

    /**
     */
    async listClients(requestParameters: ListClientsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListClientsResponseBaseResponse> {
        const response = await this.listClientsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
